# These are supported funding model platforms

github: [Kenshi2727] # Your GitHub Sponsors username
patreon: abhishekmathur # Replace with your actual Patreon username if you have one
ko_fi: abhishekmathur # Replace with your actual Ko-fi username if available
buy_me_a_coffee: abhishekmathur # Replace if you have a different Buy Me a Coffee username
custom: ['https://paypal.me/abhishekmathur'] # Custom donation link (e.g., PayPal)
